# Ubuntu Trusty support
dist: trusty

os:
    - linux

notifications:
    email:
        on_success: never
        on_failure: always

install:
    - sudo apt-get -qq update
    - sudo ./derptex-latex/install_latex.sh YES

script:
    - make all
    - make copy OUT=DerpTeX-LaTeX-out
    - ls -l DerpTeX-LaTeX-out
