sudo: required

notifications:
    email:
        on_success: never
        on_failure: always

services:
  - docker

env:
    matrix:
        - DISTRO=fedora23
        - DISTRO=fedora24
        - DISTRO=fedora25
    global:
        - IMAGE="idelsink/mexdown"
        - NAME="mexdown"
        - EXEC="docker exec $NAME"

before_install:
    - docker pull $IMAGE:$DISTRO
    - docker run --name $NAME -it -d $IMAGE:$DISTRO sh
    - export WORKDIR=$($EXEC pwd)
    - docker cp ./ $NAME:$WORKDIR

install:
    - $EXEC sudo ./mexdown/install_latex.sh YES

script:
    - $EXEC make all
    - $EXEC make copy OUT=mexdown-out
    - $EXEC ls -l mexdown-out
