notifications:
    email:
        on_success: never
        on_failure: always

sudo: required

services:
  - docker

env:
    matrix:
        - DISTRO=fedora24
    global:
        - IMAGE="idelsink/derptex-latex"
        - NAME="derptex-latex"
        - EXEC="docker exec $NAME"

before_install:
    - docker pull $IMAGE:$DISTRO
    - docker run --name $NAME -it -d $IMAGE:$DISTRO bash
    - export WORKDIR=$($EXEC bash -c 'echo $PWD')
    - docker cp ./ $NAME:$WORKDIR

install:
    - $EXEC sudo dnf -y update
    - $EXEC sudo ./derptex-latex/install_latex.sh YES

script:
    - $EXEC make all
    - $EXEC make copy OUT=DerpTeX-LaTeX-out
    - $EXEC ls -l DerpTeX-LaTeX-out
